name: flutter_latex

description: A Flutter Package to render Mathematics / Maths, Physics and Chemistry, Statistics Equations and expressions based on LaTeX, TeX, and MathML with HTML and JavaScript support.

version: 0.0.3

homepage: https://github.com/territoryfan/flutter_latex

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"


dependencies:
  webview_flutter_plus: ^0.3.0+2
  markdown: ^4.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
    - packages/flutter_latex/js/flutter_latex.js
    - packages/flutter_latex/js/flutter_latex.css

# Katex
    - packages/flutter_latex/js/katex/index.html
    - packages/flutter_latex/js/katex/katex.min.js
    - packages/flutter_latex/js/katex/katex.min.css
    - packages/flutter_latex/js/katex/auto-render.min.js
    - packages/flutter_latex/js/katex/mhchem.min.js
    - packages/flutter_latex/js/katex/fonts/KaTeX_AMS-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_AMS-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_AMS-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Caligraphic-Bold.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Caligraphic-Bold.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Caligraphic-Bold.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Caligraphic-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Caligraphic-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Caligraphic-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Fraktur-Bold.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Fraktur-Bold.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Fraktur-Bold.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Fraktur-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Fraktur-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Fraktur-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-BoldItalic.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-BoldItalic.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-BoldItalic.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Bold.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Bold.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Bold.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Italic.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Italic.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Italic.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Main-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Math-BoldItalic.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Math-BoldItalic.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Math-BoldItalic.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Math-Italic.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Math-Italic.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Math-Italic.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Bold.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Bold.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Bold.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Italic.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Italic.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Italic.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_SansSerif-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Script-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Script-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Script-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size1-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size1-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size1-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size2-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size2-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size2-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size3-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size3-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size3-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size4-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size4-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Size4-Regular.woff2
    - packages/flutter_latex/js/katex/fonts/KaTeX_Typewriter-Regular.ttf
    - packages/flutter_latex/js/katex/fonts/KaTeX_Typewriter-Regular.woff
    - packages/flutter_latex/js/katex/fonts/KaTeX_Typewriter-Regular.woff2
